global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Frontend service
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/api/metrics'

  # FastAPI backend service
  - job_name: 'fastapi-service'
    static_configs:
      - targets: ['fastapi-service:8000']
    metrics_path: '/metrics'

  # Node.js backend service
  - job_name: 'nodejs-service'
    static_configs:
      - targets: ['nodejs-service:8001']
    metrics_path: '/metrics'

  # AI/ML service
  - job_name: 'ai-ml-service'
    static_configs:
      - targets: ['ai-ml-service:8002']
    metrics_path: '/metrics'

  # Blockchain service
  - job_name: 'blockchain-service'
    static_configs:
      - targets: ['blockchain-node:8545']
    metrics_path: '/metrics'

  # PostgreSQL database
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # MongoDB database
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']

  # Redis cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Nginx reverse proxy
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
